select *
from app.warehouselocationdetail
where description like '%item-img-url-fail%';

-- do $$
-- BEGIN
 
-- 	END IF;

-- insert enabled alerts without payload
--  item-img-url-fail.


insert into app.warehouselocationdetail(description, longdescription, warehouseid, requesttypeid, createdby, lastupdatedby) 
    select rt.description, rt.description, w.warehouseid,  rt.requesttypeid, 'sysuser', 'sysuser' 
        from app.warehouselocation w, app.requesttype rt 
        where w.warehouseshortname not in ('DEFAULTS', 'PRODEV') 
        and rt.description = 'item-img-url-fail' 
        and not exists (select 1 from app.warehouselocationdetail r 
                            where r.requesttypeid = rt.requesttypeid 
                            and r.warehouseid = w.warehouseid);







-- Check if enabled alerts were properly inserted

 
  

select *
	from app.warehouselocationdetail wld, app.warehouselocation wl
	where wld.description like ('%item-img-url-fail')
	AND wld.warehouseid = wl.warehouseid 
	order by wl.warehouseshortname






-- insert payload for enabled alerts:

--  item-img-url-fail.

--  Named queries (only (ALL) as of writing)
--   ALL



update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='ABQ') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='ARK') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='ASH') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='ATL') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='AUB') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='CCR') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='COL') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='DEN') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='DFB') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='ELP') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='FAR') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='GRP') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='HAW') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='HOU') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='IND') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='JAC') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='JES') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='KAP') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='KAU') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='LAF') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='LIV') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='LOU') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='LUB') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='MAU') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='NEW') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='OAH') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='OKL') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='OMA') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='ORL') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='PEN') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='PHO') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='POR') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='ROM') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='SAA') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='SIO') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='TAM') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='TOL') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');
update app.warehouselocationdetail set payload = '{ "emailContent": {"subject":"Splunk Alert: Item Image URL Failure","fromEmail":"noreply@rndc-usa.com","toEmail":"wmsinternal@RNDC-USA.COM, WMSadmin@RNDC-USA.COM, WMSMSPSupport@RNDC-USA.COM","sections":[{"htmlHeader":"<h2 style=\"margin:0;\">TBD</h2>"},{"introHtml":"created.in.the.python.code"},{"tableHtml":{"tableHeaders":["ITEM_ID", "IMAGE_URL"],"tableRows":[]}},{"footerHtml":"<h2 style=\"margin:0;\">FOOTER.TBD</h2>"}]}, "allOption": [{"sql": "SELECT ITEM_ID, IMAGE_URL FROM default_item_master.ITE_ITEM WHERE PROFILE_ID LIKE concat(%(orgId)s , ''_Org_Profile%%'')"},{"days": "0"}]}' where warehouseid = (select w.warehouseid from app.warehouselocation w where w.warehouseshortname='WSD') and requesttypeid=(select rt.requesttypeid from app.requesttype rt where rt.description='item-img-url-fail');






-- (Unnamed)
--  Disabled queries

 

-- Check and ensure right payloads are inserted and not affecting other unrelated records


select wld.payload, wl.warehouseshortname, wld.description
from app.warehouselocationdetail wld join app.warehouselocation wl
on wld.warehouseid = wl.warehouseid 
where description != 'item-img-url-fail'
and wld.payload is not null
-- order by wld.payload




select  wld.payload, wl.warehouseshortname, wld.description
from app.warehouselocationdetail wld join app.warehouselocation wl
on wld.warehouseid = wl.warehouseid 
where description = 'item-img-url-fail'
and wld.payload is not null
order by wld.lastupdatedon



-- Test to ensure payloads can successfully be converted to JSON

SELECT *
FROM (
    SELECT 
        wd.*, 
        row_number() OVER () AS rn
    FROM app.warehouselocationdetail wd
	where description = 'item-img-url-fail'
) t 
where (payload::jsonb IS NOT NULL);
