<<<<<<< Updated upstream
SELECT * FROM app.crontasks
ORDER BY crontaskid ASC 
=======
SELECT * FROM app.crontasks 
ORDER BY description ASC 
>>>>>>> Stashed changes

 
-- insert into app.crontasks (description, longdescription, requesttypeid) 
-- 	select 'DB Alert: Static Route Missing Threshold Value' description, 
-- 		'DB Alert: Static Route Missing Threshold Value' longdescription,
-- 		rt.requesttypeid
-- 	from app.requesttype rt
-- 	where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: Static Route Missing Threshold Value')
-- 		and rt.description = 'db-alert-static-route-missing-threshold';
<<<<<<< Updated upstream
=======
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'Allocated Lpns With No Open Task Details Api Failure' description,  'Allocated Lpns With No Open Task Details Api Failure' longdescription, rt.requesttypeid, (select rt2.requesttypeid from app.requesttype rt2 where rt2.description = 'CRON Scheduling Dashboard') from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'Allocated Lpns With No Open Task Details Api Failure') and rt.description = 'lpns-no-task-api-fail';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'FS: Alpha Asn Error' description,  'FS: Alpha Asn Error' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'FS: Alpha Asn Error') and rt.description = 'fs-alpha-asn-error';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'FS: Alpha Open/Error Asn' description,  'FS: Alpha Open/Error Asn' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'FS: Alpha Open/Error Asn') and rt.description = 'fs-alpha-open-err-asn';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'FS: Alpha Open Returns' description,  'FS: Alpha Open Returns' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'FS: Alpha Open Returns') and rt.description = 'fs-alpha-open-returns';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'Divert Confirmation Down' description,  'Divert Confirmation Down' longdescription, rt.requesttypeid, (select rt2.requesttypeid from app.requesttype rt2 where rt2.description = 'CRON Scheduling Dashboard') from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'Divert Confirmation Down') and rt.description = 'divert-conf-down';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'Endpoint Queue Failures' description,  'Endpoint Queue Failures' longdescription, rt.requesttypeid, (select rt2.requesttypeid from app.requesttype rt2 where rt2.description = 'CRON Scheduling Dashboard') from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'Endpoint Queue Failures') and rt.description = 'endpoint-queue-fail';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'Endpoint Status' description,  'Endpoint Status' longdescription, rt.requesttypeid, (select rt2.requesttypeid from app.requesttype rt2 where rt2.description = 'CRON Scheduling Dashboard') from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'Endpoint Status') and rt.description = 'endpoint-status';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'Ilpns With Negative Allocated Quantity Api Failure' description,  'Ilpns With Negative Allocated Quantity Api Failure' longdescription, rt.requesttypeid, (select rt2.requesttypeid from app.requesttype rt2 where rt2.description = 'CRON Scheduling Dashboard') from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'Ilpns With Negative Allocated Quantity Api Failure') and rt.description = 'ilpns-neg-alloc';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'Item Image Url Failure' description,  'Item Image Url Failure' longdescription, rt.requesttypeid, (select rt2.requesttypeid from app.requesttype rt2 where rt2.description = 'CRON Scheduling Dashboard') from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'Item Image Url Failure') and rt.description = 'item-img-url-fail';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: Static Route UI Missing Dflt Value' description,  'DB Alert: Static Route UI Missing Dflt Value' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: Static Route UI Missing Dflt Value') and rt.description = 'db-alert-route-ui-dflt-miss';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: Routes With Multiple Wave Numbers' description,  'DB Alert: Routes With Multiple Wave Numbers' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: Routes With Multiple Wave Numbers') and rt.description = 'db-alert-routes-multi-wave';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: Item Loc Prod' description,  'DB Alert: Item Loc Prod' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: Item Loc Prod') and rt.description = 'db-alert-itemloc-prd';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'Location Rebuild Failure' description,  'Location Rebuild Failure' longdescription, rt.requesttypeid, (select rt2.requesttypeid from app.requesttype rt2 where rt2.description = 'CRON Scheduling Dashboard') from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'Location Rebuild Failure') and rt.description = 'loc-rebuild-fail';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: Duplicate PIX In Middleware WMS' description,  'DB Alert: Duplicate PIX In Middleware WMS' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: Duplicate PIX In Middleware WMS') and rt.description = 'db-alert-dup-pix-mw-wms';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: Duplicate Ship Confirm' description,  'DB Alert: Duplicate Ship Confirm' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: Duplicate Ship Confirm') and rt.description = 'db-alert-dup-ship-conf';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'Lpns With Consumed/Cancelled Allocated Quantity Api Failure' description,  'Lpns With Consumed/Cancelled Allocated Quantity Api Failure' longdescription, rt.requesttypeid, (select rt2.requesttypeid from app.requesttype rt2 where rt2.description = 'CRON Scheduling Dashboard') from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'Lpns With Consumed/Cancelled Allocated Quantity Api Failure') and rt.description = 'lpns-consumed-api';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: Inventory Adjustment Pix Missing Reason Code' description,  'DB Alert: Inventory Adjustment Pix Missing Reason Code' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: Inventory Adjustment Pix Missing Reason Code') and rt.description = 'db-alert-inv-adj-miss-rc';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: Item Level Receipts With 0 Quantity' description,  'DB Alert: Item Level Receipts With 0 Quantity' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: Item Level Receipts With 0 Quantity') and rt.description = 'db-alert-item-rcpt-zero';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'Open Pick Pack Task Details Api Failure' description,  'Open Pick Pack Task Details Api Failure' longdescription, rt.requesttypeid, (select rt2.requesttypeid from app.requesttype rt2 where rt2.description = 'CRON Scheduling Dashboard') from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'Open Pick Pack Task Details Api Failure') and rt.description = 'pickpack-api-fail';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'FS: Asw Open Returns' description,  'FS: Asw Open Returns' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'FS: Asw Open Returns') and rt.description = 'fs-asw-open-returns';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'Open Task Api Failure' description,  'Open Task Api Failure' longdescription, rt.requesttypeid, (select rt2.requesttypeid from app.requesttype rt2 where rt2.description = 'CRON Scheduling Dashboard') from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'Open Task Api Failure') and rt.description = 'open-task-api-fail';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'Open Task Details Api Failure' description,  'Open Task Details Api Failure' longdescription, rt.requesttypeid, (select rt2.requesttypeid from app.requesttype rt2 where rt2.description = 'CRON Scheduling Dashboard') from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'Open Task Details Api Failure') and rt.description = 'taskdet-api-fail';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: Long Running Or Aborted Waves' description,  'DB Alert: Long Running Or Aborted Waves' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: Long Running Or Aborted Waves') and rt.description = 'db-alert-waves-long-abort';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: Missing Item Level Verification Pix' description,  'DB Alert: Missing Item Level Verification Pix' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: Missing Item Level Verification Pix') and rt.description = 'db-alert-miss-item-verif';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'FS: ELP ASW - Pending Shipment Quantities > 1 Week' description,  'FS: ELP ASW - Pending Shipment Quantities > 1 Week' longdescription, rt.requesttypeid, (select rt2.requesttypeid from app.requesttype rt2 where rt2.description = 'CRON Scheduling Dashboard') from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'FS: ELP ASW - Pending Shipment Quantities > 1 Week') and rt.description = 'fs-asw-pend-ship1w';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'Pick Locations With Negative Tbf Api Failure' description,  'Pick Locations With Negative Tbf Api Failure' longdescription, rt.requesttypeid, (select rt2.requesttypeid from app.requesttype rt2 where rt2.description = 'CRON Scheduling Dashboard') from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'Pick Locations With Negative Tbf Api Failure') and rt.description = 'pick-neg-tbf-api';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'Pick Locations With Tbf Quantity And No Open Task Details Api Failure' description,  'Pick Locations With Tbf Quantity And No Open Task Details Api Failure' longdescription, rt.requesttypeid, (select rt2.requesttypeid from app.requesttype rt2 where rt2.description = 'CRON Scheduling Dashboard') from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'Pick Locations With Tbf Quantity And No Open Task Details Api Failure') and rt.description = 'pick-tbf-no-task';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'Putaway Task Details Api Failure' description,  'Putaway Task Details Api Failure' longdescription, rt.requesttypeid, (select rt2.requesttypeid from app.requesttype rt2 where rt2.description = 'CRON Scheduling Dashboard') from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'Putaway Task Details Api Failure') and rt.description = 'putaway-api-fail';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'Recoup Sorting Update Api Failure' description,  'Recoup Sorting Update Api Failure' longdescription, rt.requesttypeid, (select rt2.requesttypeid from app.requesttype rt2 where rt2.description = 'CRON Scheduling Dashboard') from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'Recoup Sorting Update Api Failure') and rt.description = 'recoup-sort-api';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: Routed Orders Cancelled' description,  'DB Alert: Routed Orders Cancelled' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: Routed Orders Cancelled') and rt.description = 'db-alert-routed-cancelled';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: MAWM PIX Specification Found > 1 Hour' description,  'DB Alert: MAWM PIX Specification Found > 1 Hour' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: MAWM PIX Specification Found > 1 Hour') and rt.description = 'db-alert-pix-spec-gt1h';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: MAWM Unprocessed Or Failed Ship Confirms Last 24 Hours' description,  'DB Alert: MAWM Unprocessed Or Failed Ship Confirms Last 24 Hours' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: MAWM Unprocessed Or Failed Ship Confirms Last 24 Hours') and rt.description = 'db-alert-shipconf-24h-fail';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'Slotting Item Demand Pack Failure' description,  'Slotting Item Demand Pack Failure' longdescription, rt.requesttypeid, (select rt2.requesttypeid from app.requesttype rt2 where rt2.description = 'CRON Scheduling Dashboard') from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'Slotting Item Demand Pack Failure') and rt.description = 'slot-pack-fail';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'Slotting Item Demand Unit Failure' description,  'Slotting Item Demand Unit Failure' longdescription, rt.requesttypeid, (select rt2.requesttypeid from app.requesttype rt2 where rt2.description = 'CRON Scheduling Dashboard') from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'Slotting Item Demand Unit Failure') and rt.description = 'slot-unit-fail';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'Slotting Lia Delete Pk Records Api Failure' description,  'Slotting Lia Delete Pk Records Api Failure' longdescription, rt.requesttypeid, (select rt2.requesttypeid from app.requesttype rt2 where rt2.description = 'CRON Scheduling Dashboard') from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'Slotting Lia Delete Pk Records Api Failure') and rt.description = 'lia-delpk-api-fail';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: SPO Import Failure' description,  'DB Alert: SPO Import Failure' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: SPO Import Failure') and rt.description = 'db-alert-matm-spo-import';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: MAWM - Travel > 4 Mins' description,  'DB Alert: MAWM - Travel > 4 Mins' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: MAWM - Travel > 4 Mins') and rt.description = 'db-alert-abq-travel-4m';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: ASNs With No ASN Level Verification > 5 Days' description,  'DB Alert: ASNs With No ASN Level Verification > 5 Days' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: ASNs With No ASN Level Verification > 5 Days') and rt.description = 'db-alert-asn-no-verif-5d';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: iLPNS with Missing Physical Entity codeid' description,  'DB Alert: iLPNS with Missing Physical Entity codeid' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: iLPNS with Missing Physical Entity codeid') and rt.description = 'db-alert-ilpns-miss-phys';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: Location Position > Street Length' description,  'DB Alert: Location Position > Street Length' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: Location Position > Street Length') and rt.description = 'db-alert-loc-pos-street';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: Locations W/ Inventory For Items Not Assigned' description,  'DB Alert: Locations W/ Inventory For Items Not Assigned' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: Locations W/ Inventory For Items Not Assigned') and rt.description = 'db-alert-loc-inv-no-item';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: Users W/ Incorrect User Default Configuration' description,  'DB Alert: Users W/ Incorrect User Default Configuration' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: Users W/ Incorrect User Default Configuration') and rt.description = 'db-alert-user-def-config';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: MAWM - Lpn Storage Locs With Inventory Not Tied To Lpn' description,  'DB Alert: MAWM - Lpn Storage Locs With Inventory Not Tied To Lpn' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: MAWM - Lpn Storage Locs With Inventory Not Tied To Lpn') and rt.description = 'db-alert-lpn-loc-notied';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'User Task Group Bulk Import Failure' description,  'User Task Group Bulk Import Failure' longdescription, rt.requesttypeid, (select rt2.requesttypeid from app.requesttype rt2 where rt2.description = 'CRON Scheduling Dashboard') from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'User Task Group Bulk Import Failure') and rt.description = 'taskgrp-bulk-fail';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: MAWM - Pallet Lpns W/ Inventory Records' description,  'DB Alert: MAWM - Pallet Lpns W/ Inventory Records' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: MAWM - Pallet Lpns W/ Inventory Records') and rt.description = 'db-alert-pallet-lpns-inv';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: MAWM - Olpns W/ Multiple Details Of The Same Item' description,  'DB Alert: MAWM - Olpns W/ Multiple Details Of The Same Item' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: MAWM - Olpns W/ Multiple Details Of The Same Item') and rt.description = 'db-alert-olpn-multi-det';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: Open Order In Wm > 1 Week' description,  'DB Alert: Open Order In Wm > 1 Week' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: Open Order In Wm > 1 Week') and rt.description = 'db-alert-open-order-1w';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: MAWM - Multiple Order Lines Per Original Order Line' description,  'DB Alert: MAWM - Multiple Order Lines Per Original Order Line' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: MAWM - Multiple Order Lines Per Original Order Line') and rt.description = 'db-alert-multi-ord-lines';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'Mark Dynamic Case Pick' description,  'Mark Dynamic Case Pick' longdescription, rt.requesttypeid, (select rt2.requesttypeid from app.requesttype rt2 where rt2.description = 'CRON Scheduling Dashboard') from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'Mark Dynamic Case Pick') and rt.description = 'dyn-casepick';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'Mark Dynamic Wine' description,  'Mark Dynamic Wine' longdescription, rt.requesttypeid, (select rt2.requesttypeid from app.requesttype rt2 where rt2.description = 'CRON Scheduling Dashboard') from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'Mark Dynamic Wine') and rt.description = 'dyn-wine-pick';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: MAWM - Items Weight With Large Dimensions' description,  'DB Alert: MAWM - Items Weight With Large Dimensions' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: MAWM - Items Weight With Large Dimensions') and rt.description = 'db-alert-item-wt-large';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: MAWM - Items Volume With Large Dimensions' description,  'DB Alert: MAWM - Items Volume With Large Dimensions' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: MAWM - Items Volume With Large Dimensions') and rt.description = 'db-alert-item-vol-large';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'FS: Alpha Open Adjustments > 45 Days' description,  'FS: Alpha Open Adjustments > 45 Days' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'FS: Alpha Open Adjustments > 45 Days') and rt.description = 'fs-alpha-adj-45d';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: Travel > 4 Mins' description,  'DB Alert: Travel > 4 Mins' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: Travel > 4 Mins') and rt.description = 'db-alert-travel-4m';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: Shipped Olpn W/ Consolidation Location Assignment' description,  'DB Alert: Shipped Olpn W/ Consolidation Location Assignment' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: Shipped Olpn W/ Consolidation Location Assignment') and rt.description = 'db-alert-olpn-cons-loc';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: Temporary Reserve Locations W/ Assignments, But No Inventory' description,  'DB Alert: Temporary Reserve Locations W/ Assignments, But No Inventory' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: Temporary Reserve Locations W/ Assignments, But No Inventory') and rt.description = 'db-alert-tmp-resv-no-inv';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: Temporary Reserve Locations W/ Inventory, But No Assignments' description,  'DB Alert: Temporary Reserve Locations W/ Inventory, But No Assignments' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: Temporary Reserve Locations W/ Inventory, But No Assignments') and rt.description = 'db-alert-tmp-inv-no-resv';
-- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) 
-- select 'DB Alert: MAWM - Duplicate Pix''s In Middleware Wms' description,
-- 'DB Alert: MAWM - Duplicate Pix''s In Middleware Wms' longdescription, 
-- rt.requesttypeid, 
-- null 
-- from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: MAWM - Duplicate Pix''s In Middleware Wms') and rt.description = 'db-alert-por-dup-pix';
-- -- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: MAWM -Inventory Adjustment Pix W/ Null Po Line' description,  'DB Alert: MAWM -Inventory Adjustment Pix W/ Null Po Line' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: MAWM -Inventory Adjustment Pix W/ Null Po Line') and rt.description = 'db-alert-inv-adj-null-po';
-- -- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: MAWM -In Packing Olpns > 5 Minutes' description,  'DB Alert: MAWM -In Packing Olpns > 5 Minutes' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: MAWM -In Packing Olpns > 5 Minutes') and rt.description = 'db-alert-packing-olpn-5m';
-- -- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: MAWM -Loaded Shipments W/ No Ship Confirm > 6 Hours' description,  'DB Alert: MAWM -Loaded Shipments W/ No Ship Confirm > 6 Hours' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: MAWM -Loaded Shipments W/ No Ship Confirm > 6 Hours') and rt.description = 'db-alert-load-no-ship-6h';
-- -- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: MAWM -Putaway Task Is Open But Ilpn Is Putaway' description,  'DB Alert: MAWM -Putaway Task Is Open But Ilpn Is Putaway' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: MAWM -Putaway Task Is Open But Ilpn Is Putaway') and rt.description = 'db-alert-putaway-open-ilpn';
-- -- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: MAWM -Task Completed Or Cancelled W/ Open Task Details' description,  'DB Alert: MAWM -Task Completed Or Cancelled W/ Open Task Details' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: MAWM -Task Completed Or Cancelled W/ Open Task Details') and rt.description = 'db-alert-taskcomp-open-det';
-- -- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: MAWM -Task Open W/ Completed Or Cancelled Task Details' description,  'DB Alert: MAWM -Task Open W/ Completed Or Cancelled Task Details' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: MAWM -Task Open W/ Completed Or Cancelled Task Details') and rt.description = 'db-alert-taskopen-compdet';
-- -- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'DB Alert: MAWM -Task In Progress W/ Completed Or Cancelled Task Details' description,  'DB Alert: MAWM -Task In Progress W/ Completed Or Cancelled Task Details' longdescription, rt.requesttypeid, null from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'DB Alert: MAWM -Task In Progress W/ Completed Or Cancelled Task Details') and rt.description = 'db-alert-taskprog-compdet';
-- -- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'MAWM Consolidation Report' description,  'MAWM Consolidation Report' longdescription, rt.requesttypeid, (select rt2.requesttypeid from app.requesttype rt2 where rt2.description = 'CRON Scheduling Dashboard') from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'MAWM Consolidation Report') and rt.description = 'mawm-cons-report';
-- -- insert into app.crontasks (description, longdescription, requesttypeid, ParentRequestTypeId) select 'Update Ext Display Barcode' description,  'Update Ext Display Barcode' longdescription, rt.requesttypeid, (select rt2.requesttypeid from app.requesttype rt2 where rt2.description = 'CRON Scheduling Dashboard') from app.requesttype rt  where not exists (select 1 from app.crontasks c where c.description = 'Update Ext Display Barcode') and rt.description = 'upd-ext-barcode';

-- select *
-- from app.crontasks
-- where description = 'Update Ext Display Barcode';
>>>>>>> Stashed changes


-- select *
-- from app.crontasks
-- where description = 'DB Alert: MAWM - Duplicate Pix''s In Middleware Wms' 

<<<<<<< Updated upstream

=======
>>>>>>> Stashed changes
