SELECT * FROM app.statemachinerepo
ORDER BY statemchinerepoid ASC 


insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'lpns-no-task-api-fail' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-lpns-no-task-api-fail');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'fs-alpha-asn-error' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-fs-alpha-asn-error');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'fs-alpha-open-err-asn' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-fs-alpha-open-err-asn');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'fs-alpha-open-returns' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-fs-alpha-open-returns');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'divert-conf-down' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-divert-conf-down');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'endpoint-queue-fail' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-endpoint-queue-fail');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'endpoint-status' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-endpoint-status');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'ilpns-neg-alloc' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-ilpns-neg-alloc');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'item-img-url-fail' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-item-img-url-fail');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'loc-rebuild-fail' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-loc-rebuild-fail');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'lpns-consumed-api' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-lpns-consumed-api');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'pickpack-api-fail' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-pickpack-api-fail');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'fs-asw-open-returns' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-fs-asw-open-returns');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'open-task-api-fail' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-open-task-api-fail');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'taskdet-api-fail' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-taskdet-api-fail');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'fs-asw-pend-ship1w' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-fs-asw-pend-ship1w');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'pick-neg-tbf-api' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-pick-neg-tbf-api');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'pick-tbf-no-task' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-pick-tbf-no-task');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'putaway-api-fail' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-putaway-api-fail');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'recoup-sort-api' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-recoup-sort-api');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'slot-pack-fail' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-slot-pack-fail');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'slot-unit-fail' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-slot-unit-fail');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'lia-delpk-api-fail' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-lia-delpk-api-fail');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'taskgrp-bulk-fail' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-taskgrp-bulk-fail');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'dyn-casepick' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-dyn-casepick');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'dyn-wine-pick' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-dyn-wine-pick');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'fs-alpha-adj-45d' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-fs-alpha-adj-45d');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'mawm-cons-report' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-mawm-cons-report');
insert into app.statemachinerepo(statemachine, description, requesttypeid) select 'tbd-' || rt.description, 'tbd-' || rt.description, rt.requesttypeid from app.requesttype rt where rt.description = 'upd-ext-barcode' and not exists (select 1 from app.statemachinerepo sr where sr.description = 'tbd-upd-ext-barcode');
