

select *
from app.cronaction
<<<<<<< Updated upstream
order by cronactionid

=======
order by payload

-- select *
-- from app.cronaction
-- where payload like '%Duplicate Pixs%'
>>>>>>> Stashed changes


-- insert into app.cronaction (
-- 		CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy)
-- 	select 
-- 		c.crontaskid,
-- 		cat.CronActionTypeId,
-- 		'{"EmailTextOnError":"tbd","TaskName":"DB Alert: Static Route Missing Threshold Value","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-static-route-missing-threshold"}',
-- 		'sysuser', 'sysuser'
-- 	from 
-- 		app.cronactiontype cat, app.crontasks c
-- 	where
-- 		c.description = 'DB Alert: Static Route Missing Threshold Value'
-- 		and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid)
-- 		and cat.description = 'NONE';
<<<<<<< Updated upstream
=======





-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"Allocated Lpns With No Open Task Details Api Failure","StateMachine":"wms-tools-state-machine-lpns-no-task-api-fail","Lambda":"wms-tools-lambda-lpns-no-task-api-fail","RequestType":"lpns-no-task-api-fail"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'Allocated Lpns With No Open Task Details Api Failure' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"FS: Alpha Asn Error","StateMachine":"wms-tools-state-machine-fs-alpha-asn-error","Lambda":"wms-tools-lambda-fs-alpha-asn-error","RequestType":"fs-alpha-asn-error"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'FS: Alpha Asn Error' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"FS: Alpha Open/Error Asn","StateMachine":"wms-tools-state-machine-fs-alpha-open-err-asn","Lambda":"wms-tools-lambda-fs-alpha-open-err-asn","RequestType":"fs-alpha-open-err-asn"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'FS: Alpha Open/Error Asn' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"FS: Alpha Open Returns","StateMachine":"wms-tools-state-machine-fs-alpha-open-returns","Lambda":"wms-tools-lambda-fs-alpha-open-returns","RequestType":"fs-alpha-open-returns"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'FS: Alpha Open Returns' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"Divert Confirmation Down","StateMachine":"wms-tools-state-machine-divert-conf-down","Lambda":"wms-tools-lambda-divert-conf-down","RequestType":"divert-conf-down"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'Divert Confirmation Down' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"Endpoint Queue Failures","StateMachine":"wms-tools-state-machine-endpoint-queue-fail","Lambda":"wms-tools-lambda-endpoint-queue-fail","RequestType":"endpoint-queue-fail"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'Endpoint Queue Failures' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"Endpoint Status","StateMachine":"wms-tools-state-machine-endpoint-status","Lambda":"wms-tools-lambda-endpoint-status","RequestType":"endpoint-status"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'Endpoint Status' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"Ilpns With Negative Allocated Quantity Api Failure","StateMachine":"wms-tools-state-machine-ilpns-neg-alloc","Lambda":"wms-tools-lambda-ilpns-neg-alloc","RequestType":"ilpns-neg-alloc"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'Ilpns With Negative Allocated Quantity Api Failure' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"Item Image Url Failure","StateMachine":"wms-tools-state-machine-item-img-url-fail","Lambda":"wms-tools-lambda-item-img-url-fail","RequestType":"item-img-url-fail"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'Item Image Url Failure' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"Location Rebuild Failure","StateMachine":"wms-tools-state-machine-loc-rebuild-fail","Lambda":"wms-tools-lambda-loc-rebuild-fail","RequestType":"loc-rebuild-fail"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'Location Rebuild Failure' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"Lpns With Consumed/Cancelled Allocated Quantity Api Failure","StateMachine":"wms-tools-state-machine-lpns-consumed-api","Lambda":"wms-tools-lambda-lpns-consumed-api","RequestType":"lpns-consumed-api"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'Lpns With Consumed/Cancelled Allocated Quantity Api Failure' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';

-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"Open Pick Pack Task Details Api Failure","StateMachine":"wms-tools-state-machine-pickpack-api-fail","Lambda":"wms-tools-lambda-pickpack-api-fail","RequestType":"pickpack-api-fail"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'Open Pick Pack Task Details Api Failure' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"FS: Asw Open Returns","StateMachine":"wms-tools-state-machine-fs-asw-open-returns","Lambda":"wms-tools-lambda-fs-asw-open-returns","RequestType":"fs-asw-open-returns"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'FS: Asw Open Returns' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"Open Task Api Failure","StateMachine":"wms-tools-state-machine-open-task-api-fail","Lambda":"wms-tools-lambda-open-task-api-fail","RequestType":"open-task-api-fail"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'Open Task Api Failure' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"Open Task Details Api Failure","StateMachine":"wms-tools-state-machine-taskdet-api-fail","Lambda":"wms-tools-lambda-taskdet-api-fail","RequestType":"taskdet-api-fail"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'Open Task Details Api Failure' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';


-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"FS: ELP ASW - Pending Shipment Quantities > 1 Week","StateMachine":"wms-tools-state-machine-fs-asw-pend-ship1w","Lambda":"wms-tools-lambda-fs-asw-pend-ship1w","RequestType":"fs-asw-pend-ship1w"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'FS: ELP ASW - Pending Shipment Quantities > 1 Week' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"Pick Locations With Negative Tbf Api Failure","StateMachine":"wms-tools-state-machine-pick-neg-tbf-api","Lambda":"wms-tools-lambda-pick-neg-tbf-api","RequestType":"pick-neg-tbf-api"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'Pick Locations With Negative Tbf Api Failure' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"Pick Locations With Tbf Quantity And No Open Task Details Api Failure","StateMachine":"wms-tools-state-machine-pick-tbf-no-task","Lambda":"wms-tools-lambda-pick-tbf-no-task","RequestType":"pick-tbf-no-task"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'Pick Locations With Tbf Quantity And No Open Task Details Api Failure' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"Putaway Task Details Api Failure","StateMachine":"wms-tools-state-machine-putaway-api-fail","Lambda":"wms-tools-lambda-putaway-api-fail","RequestType":"putaway-api-fail"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'Putaway Task Details Api Failure' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"Recoup Sorting Update Api Failure","StateMachine":"wms-tools-state-machine-recoup-sort-api","Lambda":"wms-tools-lambda-recoup-sort-api","RequestType":"recoup-sort-api"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'Recoup Sorting Update Api Failure' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';

-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"Slotting Item Demand Pack Failure","StateMachine":"wms-tools-state-machine-slot-pack-fail","Lambda":"wms-tools-lambda-slot-pack-fail","RequestType":"slot-pack-fail"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'Slotting Item Demand Pack Failure' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"Slotting Item Demand Unit Failure","StateMachine":"wms-tools-state-machine-slot-unit-fail","Lambda":"wms-tools-lambda-slot-unit-fail","RequestType":"slot-unit-fail"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'Slotting Item Demand Unit Failure' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"Slotting Lia Delete Pk Records Api Failure","StateMachine":"wms-tools-state-machine-lia-delpk-api-fail","Lambda":"wms-tools-lambda-lia-delpk-api-fail","RequestType":"lia-delpk-api-fail"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'Slotting Lia Delete Pk Records Api Failure' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"User Task Group Bulk Import Failure","StateMachine":"wms-tools-state-machine-taskgrp-bulk-fail","Lambda":"wms-tools-lambda-taskgrp-bulk-fail","RequestType":"taskgrp-bulk-fail"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'User Task Group Bulk Import Failure' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"Mark Dynamic Case Pick","StateMachine":"wms-tools-state-machine-dyn-casepick","Lambda":"wms-tools-lambda-dyn-casepick","RequestType":"dyn-casepick"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'Mark Dynamic Case Pick' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';

-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"Mark Dynamic Wine","StateMachine":"wms-tools-state-machine-dyn-wine-pick","Lambda":"wms-tools-lambda-dyn-wine-pick","RequestType":"dyn-wine-pick"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'Mark Dynamic Wine' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"FS: Alpha Open Adjustments > 45 Days","StateMachine":"wms-tools-state-machine-fs-alpha-adj-45d","Lambda":"wms-tools-lambda-alpha-adj-45d","RequestType":"fs-alpha-adj-45d"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'FS: Alpha Open Adjustments > 45 Days' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"MAWM Consolidation Report","StateMachine":"wms-tools-state-machine-mawm-cons-report","Lambda":"wms-tools-lambda-mawm-cons-report","RequestType":"mawm-cons-report"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'MAWM Consolidation Report' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) 
-- 		select c.crontaskid, 
-- 		cat.CronActionTypeId,
-- 		'{"EmailTextOnError":"tbd","TaskName":"Update Ext Display Barcode","StateMachine":"wms-tools-state-machine-upd-ext-barcode","Lambda":"wms-tools-lambda-upd-ext-barcode","RequestType":"upd-ext-barcode"}',
-- 		'sysuser', 
-- 		'sysuser' 
-- 		from app.cronactiontype cat, app.crontasks c 
-- 		where c.description = 'Update Ext Display Barcode' 
-- 			and not exists (select 1 from app.cronaction c2 
-- 								where c2.crontaskid = c.crontaskid) 
-- 			and cat.description = 'NONE';







-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: Static Route UI Missing Dflt Value","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-route-ui-dflt-miss"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: Static Route UI Missing Dflt Value' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: Routes With Multiple Wave Numbers","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-routes-multi-wave"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: Routes With Multiple Wave Numbers' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: Item Loc Prod","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-oracle-db-alert","RequestType":"db-alert-itemloc-prd"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: Item Loc Prod' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: Duplicate PIX In Middleware WMS","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-oracle-db-alert","RequestType":"db-alert-dup-pix-mw-wms"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: Duplicate PIX In Middleware WMS' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: Duplicate Ship Confirm","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-oracle-db-alert","RequestType":"db-alert-dup-ship-conf"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: Duplicate Ship Confirm' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: Inventory Adjustment Pix Missing Reason Code","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-inv-adj-miss-rc"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: Inventory Adjustment Pix Missing Reason Code' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: Item Level Receipts With 0 Quantity","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-item-rcpt-zero"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: Item Level Receipts With 0 Quantity' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: Long Running Or Aborted Waves","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-waves-long-abort"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: Long Running Or Aborted Waves' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: Missing Item Level Verification Pix","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-oracle-db-alert","RequestType":"db-alert-miss-item-verif"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: Missing Item Level Verification Pix' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: Routed Orders Cancelled","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-routed-cancelled"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: Routed Orders Cancelled' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: MAWM PIX Specification Found > 1 Hour","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-pix-spec-gt1h"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: MAWM PIX Specification Found > 1 Hour' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: MAWM Unprocessed Or Failed Ship Confirms Last 24 Hours","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-shipconf-24h-fail"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: MAWM Unprocessed Or Failed Ship Confirms Last 24 Hours' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: SPO Import Failure","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-matm-spo-import"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: SPO Import Failure' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: MAWM - Travel > 4 Mins","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-oracle-db-alert","RequestType":"db-alert-abq-travel-4m"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: MAWM - Travel > 4 Mins' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: ASNs With No ASN Level Verification > 5 Days","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-oracle-db-alert","RequestType":"db-alert-asn-no-verif-5d"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: ASNs With No ASN Level Verification > 5 Days' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: iLPNS with Missing Physical Entity codeid","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-ilpns-miss-phys"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: iLPNS with Missing Physical Entity codeid' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: Location Position > Street Length","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-loc-pos-street"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: Location Position > Street Length' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: Locations W/ Inventory For Items Not Assigned","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-loc-inv-no-item"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: Locations W/ Inventory For Items Not Assigned' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: Users W/ Incorrect User Default Configuration","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-user-def-config"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: Users W/ Incorrect User Default Configuration' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: MAWM - Lpn Storage Locs With Inventory Not Tied To Lpn","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-lpn-loc-notied"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: MAWM - Lpn Storage Locs With Inventory Not Tied To Lpn' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: MAWM - Pallet Lpns W/ Inventory Records","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-pallet-lpns-inv"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: MAWM - Pallet Lpns W/ Inventory Records' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: MAWM - Olpns W/ Multiple Details Of The Same Item","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-olpn-multi-det"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: MAWM - Olpns W/ Multiple Details Of The Same Item' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: Open Order In Wm > 1 Week","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-open-order-1w"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: Open Order In Wm > 1 Week' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: MAWM - Multiple Order Lines Per Original Order Line","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-multi-ord-lines"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: MAWM - Multiple Order Lines Per Original Order Line' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: MAWM - Items Weight With Large Dimensions","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-item-wt-large"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: MAWM - Items Weight With Large Dimensions' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: MAWM - Items Volume With Large Dimensions","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-item-vol-large"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: MAWM - Items Volume With Large Dimensions' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: Travel > 4 Mins","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-travel-4m"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: Travel > 4 Mins' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: Shipped Olpn W/ Consolidation Location Assignment","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-olpn-cons-loc"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: Shipped Olpn W/ Consolidation Location Assignment' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: Temporary Reserve Locations W/ Assignments, But No Inventory","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-tmp-resv-no-inv"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: Temporary Reserve Locations W/ Assignments, But No Inventory' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: Temporary Reserve Locations W/ Inventory, But No Assignments","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-tmp-inv-no-resv"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: Temporary Reserve Locations W/ Inventory, But No Assignments' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: MAWM - Duplicate Pixs In Middleware Wms","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-por-dup-pix"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: MAWM - Duplicate Pix''s In Middleware Wms' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: MAWM -Inventory Adjustment Pix W/ Null Po Line","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-oracle-db-alert","RequestType":"db-alert-inv-adj-null-po"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: MAWM -Inventory Adjustment Pix W/ Null Po Line' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: MAWM -In Packing Olpns > 5 Minutes","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-packing-olpn-5m"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: MAWM -In Packing Olpns > 5 Minutes' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: MAWM -Loaded Shipments W/ No Ship Confirm > 6 Hours","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-load-no-ship-6h"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: MAWM -Loaded Shipments W/ No Ship Confirm > 6 Hours' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: MAWM -Putaway Task Is Open But Ilpn Is Putaway","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-putaway-open-ilpn"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: MAWM -Putaway Task Is Open But Ilpn Is Putaway' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: MAWM -Task Completed Or Cancelled W/ Open Task Details","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-taskcomp-open-det"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: MAWM -Task Completed Or Cancelled W/ Open Task Details' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: MAWM -Task Open W/ Completed Or Cancelled Task Details","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-taskopen-compdet"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: MAWM -Task Open W/ Completed Or Cancelled Task Details' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';
-- insert into app.cronaction (CronTaskId, CronActionTypeId, Payload, CreatedBy, LastUpdatedBy) select c.crontaskid, cat.CronActionTypeId,'{"EmailTextOnError":"tbd","TaskName":"DB Alert: MAWM -Task In Progress W/ Completed Or Cancelled Task Details","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-taskprog-compdet"}','sysuser', 'sysuser' from app.cronactiontype cat, app.crontasks c where c.description = 'DB Alert: MAWM -Task In Progress W/ Completed Or Cancelled Task Details' and not exists (select 1 from app.cronaction c2 where c2.crontaskid = c.crontaskid) and cat.description = 'NONE';


-- select *
-- from app.cronaction
-- where payload like '%Pix''s%'

-- update app.cronaction
-- set payload = '{"EmailTextOnError":"tbd","TaskName":"DB Alert: MAWM - Duplicate Pix''s In Middleware Wms","StateMachine":"wms-tools-state-machine-db-alert","Lambda":"wms-tools-lambda-db-alert","RequestType":"db-alert-por-dup-pix"}'
-- where cronactionid = 181

>>>>>>> Stashed changes
